name: "Reader"

on:
  workflow_dispatch:

jobs:
  test:
    name: "Test read from cache"
    runs-on: ubuntu-latest
    steps:
      - name: "Cache file 1"
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/test1
          key: my-cache-key-1

      - name: "Cache file 2"
        uses: actions/cache/restore@v4
        with:
          path: ${{ github.workspace }}/test2
          key: my-cache-key-2

      - name: "Read file 1"
        run: |
          cd ${{ github.workspace }}/test1
          pwd
          ls -la ${{ github.workspace }}/test1
          cat ${{ github.workspace }}/test1/file1.txt

      - name: "Read file 2"
        run: |
          cd ${{ github.workspace }}/test2
          pwd
          ls -la ${{ github.workspace }}/test2
          cat ${{ github.workspace }}/test2/file2.txt
