name: "Writer"

on:
  workflow_dispatch:
    inputs:
      value1:
        description: "Value 1"
        required: true
        type: string
      value2:
        description: "Value 2"
        required: true
        type: string

jobs:
  test:
    name: "Test write in cache"
    runs-on: ubuntu-latest
    steps:
      - name: "Writer file 1"
        run: |
          mkdir -p ${{ github.workspace }}/test1
          echo ${{ github.event.inputs.value1 }} > "${{ github.workspace }}/test1/file1.txt"
          pwd
          ls -la ${{ github.workspace }}/test1
          cat ${{ github.workspace }}/test1/file1.txt

      - name: "Writer file 2"
        run: |
          mkdir -p ${{ github.workspace }}/test2
          echo ${{ github.event.inputs.value1 }} > "${{ github.workspace }}/test2/file2.txt"
          pwd
          ls -la ${{ github.workspace }}/test2
          cat ${{ github.workspace }}/test2/file2.txt

      - name: "Cache file 1"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/test1
          key: my-cache-key-1

      - name: "Cache file 2"
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/test2
          key: my-cache-key-2
